### ISSUE TITLE
MySQL data deprecation?

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/smrf#127]
Should SMRF deprecate the MySQL code moving forward? This isn't something that is used much anymore due to the switch to gridded data and that none of the MySQL projects (like the database and `CorrectWxData`) are being actively maintained.

**Comment by Hedrick-ARS** [comment]
The way we set up the MySQL database was pretty ad hoc. We've always been skeptical that anyone using SMRF/AWSM would be able to implement a similar database, so I see no reason why we shouldn't deprecate the functionality since it was tailored to our use case. It seems much more likely that if someone wants to use stations for forcing input that they could just construct their own CSV files.
