### ISSUE TITLE
Remove changelog entry "gridded/zone_number-> removed" from changelog

### ISSUE THREAD

**Issue by scotthavens** [USDA-ARS-NWRC/smrf#136]
Trying to run a config file after applying the changes and it will not run saying that the `gridded/zone_number -> REMOVED`. The value is removed but still in the `CoreConfig` but saying it's removed in `changelog.ini`.

**Comment by micahjohnson150** [comment]
So the problem here is that while it is being removed before hand, it is in the coreconfig and there is a recipe (gridded_recipe) it is being added back in. And since the changelog shows it was deleted they now conflict after applying recipes. So inicheck here is actually doing the right thing. The real issue is that I didn't make the change log agree with the core config. The question here is whether we want to adjust the changelog or remove it from the coreconfig and implement #100. Thoughts?

**Comment by scotthavens** [comment]
Let's remove it from the change log for now and #100 will be the issue to remove from the core config and add to the change log.
