### ISSUE TITLE
Intermittent test failures for wind

### ISSUE THREAD

**Issue by jomey** [USDA-ARS-NWRC/smrf#180]
Tests wind in a threaded setup fail intermittently with a missing time step.
Example: https://travis-ci.com/github/USDA-ARS-NWRC/smrf/jobs/359503602

**Comment by scotthavens** [comment]
This probably still has something to do with PR #178 where the thread variables for the wind class aren't being set properly so some of them persist from test to test.

**Comment by jomey** [comment]
I am wondering, why the time comparison has one less hour than expected. How are these related with the thread variables?

**Comment by scotthavens** [comment]
Not all the thread variables for the Winstral model are used for Wind Ninja. However, they still need to be set for precipitation so if they aren't set then they can fail. It typically fails at 2 timesteps because that is the max number in the queue. Changing max queue to 1 would make it fail at 1 I bet.

**Comment by scotthavens** [comment]
Fixed with #183
