### ISSUE TITLE
Use single precision for SMRF output files

### ISSUE THREAD

**Issue by jomey** [USDA-ARS-NWRC/smrf#189]
Capturing an idea that came up with a PR review in AWSM:
@scotthavens
The problem is that the SMRF data needs to be converted before running pysnobal. Therefore, it has to happen within AWSM and not in testing. Or we do all calculations in 32-bit?

@jomey
What downside would a 32-bit calculation have? I could not think of any for the current

@scotthavens
The one downside I see is that numpy is 64-bit by default. The main problem is that iSnobal C code expects double so it'll have to be converted at some point. So a potential solution would be to have an option to do single or double precision and keep everything at 32-bit for testing.

Might actually be able to pull this off within netcdf. It appears that you can write 64-bit variable. I'll look into it but will require a new option for SMRF.

**Comment by scotthavens** [comment]
I think that leaving all the calculations in 64-bit is going to be a lot less hassle. It will take more to check and convert everything to float than is worth it. Since numpy is default 64-bit it makes sense to keep it that way.

The Python NetCDF4 library has the option to output in double which will help address the PR in AWSM that this stemmed from.
